schema_version = 1

id = "onedark-pro-blur"
name = "OneDark Pro Blur"
version = "0.0.1"

authors = ["MadKarma"]
description = "Zed OneDark Pro port with blur effects"
repository = "https://github.com/madkarmaa/zed-onedark-pro-blur"
